import { Metadata } from "next"
import { folderStructure } from "./data"
import { RenderFolder } from "./render-folder"

export const metadata: Metadata = {
  title: "Organize Folders and Routes",
  description: "Generated by create next app",
}
export default function Home() {
  return (
    <div className="p-8 border mb-auto mt-10 rounded-md w-full max-w-[444px] mx-auto shadow-xl">
      <h1 className="text-2xl font-semibold tracking-tighter">
        Project Folder
      </h1>
      <div className="menu1">
        <RenderFolder structure={[folderStructure]} />
      </div>
    </div>
  )
}
