import { Metadata } from "next"
import { PlanContent } from "./content"
export const metadata: Metadata = {
  title: "Auth.js V5 Plan",
  description: "Generated by create next app",
}
export default function PlanPage() {
  return (
    <>
      <PlanContent />
    </>
  )
}
